using System.Windows.Input;

namespace WaveLab.ViewModels;

/// <summary>
/// One line of a bound menu: what it says, what it does, and what it does it to.
/// </summary>
/// <remarks>
/// The Recent Files submenu holds paths and a fixed Clear entry, and both are data rather than
/// declared elements because a <c>MenuItem</c> written into a <c>CompositeCollection</c> is styled
/// while it belongs to no <c>ItemsControl</c> — the content-alignment bindings its theme style
/// carries then have no ancestor to find, and WPF reports two binding errors at every launch.
/// Neither a local style nor local alignment values suppress them; being generated by the menu,
/// like every other entry, does.
/// </remarks>
public sealed class MenuEntry(string text, ICommand command, object? parameter = null)
{
    /// <summary>The text as the user should read it, unescaped.</summary>
    public string Text { get; } = text;

    public ICommand Command { get; } = command;

    /// <summary>Passed to <see cref="Command"/>; null for an entry that takes no argument.</summary>
    public object? Parameter { get; } = parameter;
}
